- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(9facf577-1995-4354-b480-1c1148e24d64)'
    appType: 'webApp'
    appName: 
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'